### ISSUE TITLE
[Q] - Gulp Configuration

### ISSUE THREAD

**Issue by Altiano** [szwacz/electron-boilerplate#112]
What does bundle task do? and how can gulp always execute watch task? .. I don't understand how you do that

**Comment by szwacz** [comment]
Bundle task follows all imports in your code and combines all JS files into one big file which then will be run in the application.

Don't understand what you want to achieve in gulp watch question. You can always run it just by typing `gulp watch` but this project is configured in a way so watch makes sense only when run inside `npm start`, what happens automatically so you don't have to do anything.

**Comment by Altiano** [comment]
Why need to bundle? Is it for performance?

I found the code to do watch .. `runBuild()
.then(function () {
    runGulpWatch();
    runApp();
});`
I just curious about how all this configuration works

**Comment by szwacz** [comment]
**Bundling**

Bundling gives you nice performance boost when dealing with JS fetched from the internet (you have one file to download instead of dozens). So generally speaking - yes. In particular case of electron applications this is neglegible because all files are loaded from local disk :)

But bundling still is cool because of many other reasons:
1. Thanks to bundling you don't need to include <script> tags for each file or have any special tool which does it automatically for you - there is only one bundled file.
2. Everything loaded via <script> tag is global. Bundler allows you to load script as visible only in one place.
3. Bundling task will show you immediate error when you mistyped some path to file, or mistakenly deleted file you didn't want to delete.

Some of those reasons will be obsolete when browsers finally will implement natively ES6 Modules, then it might make more sense not to bundle code in electron app, for now in my opinion it makes sense.

**Gulp watch**
Watch to be faster doesn't build once again whole application, but does only one task to update one thing you've changed. So first `runBuild()` builds whole application, then watch kicks in, and when you save for example `.less` file gulp will run just less task to convert less to css.
Does that answer your question?

**Name of the main script**
This is the purpose of boilerplate for me, to make decision for you so you don't have to bother :) That's why this script is hardcoded as `background.js`.

**Comment by Altiano** [comment]
Yes.. I think that's all I want to know.. thanks :)
