### ISSUE TITLE
[suggestion] Add *.scss, *.jade and *.jsx file support

### ISSUE THREAD

**Issue by dariuszsikorski** [szwacz/electron-boilerplate#116]
**SCSS**: In many frameworks (I.e. _Bootstrap 4_, _Semantic Ui_) less language is beeing replaced by Scss.
Compiler: https://www.npmjs.com/package/gulp-sass

**JADE**: Personally I'm using Jade which is a Way cleaner than Html. Also every Html code snippet can be converted to Jade with online tools such as http://html2jade.vida.io
Compiler: https://www.npmjs.com/package/gulp-jade

**JSX**: Can combine html and js code in one file, _React.js_ also use this format and going that path would allow to implement popular Ui's like: http://www.material-ui.com/
Compiler [1]: https://www.npmjs.com/package/gulp-jsx
Compiler [2]: https://www.npmjs.com/package/gulp-babel

Why won't I include this compilers only for my specific project?
Compilers are contained in `/tasks/build.js` file which is outside the `/app/` folder and modifying electron-boilerplate tasks would make it difficult to get future updates of boilerplate without overwriting customized files.

This three formats may be useful for other developers too ;-)

**Temporary solution:**
I use Prepros App for compilation and store precompiled files next to the app *.js and *.html files.

**Comment by black-snow** [comment]
`resources`, `config` and others do contain customized files, too :) (at least for me they do)
Shouldn't you be able to stash your changes and merge them back in on incoming updates?

**Comment by carlosperate** [comment]
>Why won't I include this compilers only for my specific project?
Compilers are contained in /tasks/build.js file which is outside the /app/ folder and modifying electron-boilerplate tasks would make it difficult to get future updates of boilerplate without overwriting customized files.

Similarly one could argue that if the majority of users don't use these features, they either have a bloaded boilerplate, or if they remove them it makes it difficult to get future updates of boilerplate without overwriting the customized files.

**Comment by dariuszsikorski** [comment]
@carlosperate That's true, adding these compilers made my project 20mb bigger in size.

**Comment by szwacz** [comment]
I never thought people would like not to make any changes to gulp build tasks in order to keep the whole boilerplate updatable. Is it even possible? :)

Boilerplate by definition is a starting point which you need to modify and change to some extent.

The build process is split into tasks, so I see no problem in modifying one task and still be able to update one another from this repo if neccessary (by copy-paste of course).

We can talk about more modular build process, but I'm not sure this work will be appreciated by the majority.

**Comment by black-snow** [comment]
I'm quite a git-noob but couldn't one just have multiple remotes and just cherrypick?

**Comment by carlosperate** [comment]
To be fair, I've been quite negative to framework additions to the boilerplate in a lot of my comments around here, and in all honestly, as long as they are compartmentalised (as it currently is in the build file) it is a quite a straight forward procedure to remove, and maintain removed, unwanted features.

That being said, I had to "manually cherry pick" my boilerplate updates due to my project structure and general changes. So this was a process I'm used to do manually from the beginning.

So yeah, as long as this factor is kept well under consideration on the addition of new features it really shouldn't really be a problem. However, I personally would prefer the number of supported frameworks to be relatively low, in order to maintain the boilerplate light. It should be easy to add features, and not a necessity to remove them.

**Comment by black-snow** [comment]
@carlosperate I didn't intend to support the addition of more stuff to the boilerplate. Instead I tried to provide a reasonable solution for dariusz. I think the boilerplate should pretty much just cover the "least reasonable minimum" of things required to kickstart an electron project.

As for now I am manually copying the changes from the boilerplate, too. Ain't you guys firm w/ git? It should be feasible to have two remotes, the boilerplate and my custom repo, should it not?

**Comment by carlosperate** [comment]
You can pull from a remote repository (normally you'd call yours `origin` and the original `upstream`), but my project folder structure was different than the boilerplate and I did not want to maintain a git subtree, as there was a high chance I would modify and move things around the boilerplate even further (I didn't in the end though).

**Comment by szwacz** [comment]
I don't see a way to have build process always compatible with upstream (this repo), simply because for sure this project will provide breaking changes in the future. The role of boilerplate is to provide the best starting point for new projects. Thinking about backwards compatibility will make maintanance of this project a lot harder.

I've reorganised a little build files so the whole process can be more modular. Now you can easier add extra files with more gulp tasks just next to default tasks (well, the only change is that everything had moved to `tasks/build`, so I probably shouldn't advertise it as something big ;). But still the way I would use it is to manually copy parts of future versions of this project into your project.

I'll start a changelog to make keeping with changes easy.

**Comment by szwacz** [comment]
Changelog: https://github.com/szwacz/electron-boilerplate/releases

**Comment by carlosperate** [comment]
I suggest to change the newly created build folder to something different, as a lot of projects might have that directory name in their gitignore files.

**Comment by szwacz** [comment]
@carlosperate so does this project, (have ignored build folder) but somehow it works ;). I don't have better name. I'm open to suggestions.

**Comment by carlosperate** [comment]
Yeah, I cannot come up with a better name either. Maybe adding some prefix or postfix to the word "build", I had to add an explicit exception to my gitignore file to get it to show on a single `git status` or `git add .`.

**Comment by szwacz** [comment]
@carlosperate what paths for build folders do you use in gitignore?

**Comment by carlosperate** [comment]
My electron folder is a subdirectory from the project root, so at the top level I've got `/build` to be [ignored](https://github.com/carlosperate/ardublockly/blob/master/.gitignore#L95), and the build folder inside the electron boilertplate directory [as an exception](https://github.com/carlosperate/ardublockly/blob/master/.gitignore#L110) (there is also an [electron specific gitignore](https://github.com/carlosperate/ardublockly/blob/master/package/electron/.gitignore) in its directory, but without the stuff included in the main gitignore).
