### ISSUE TITLE
ARM Build

### ISSUE THREAD

**Issue by pkunze** [szwacz/electron-boilerplate#121]
Hey! Awesome Boilerplate, I love it!!! 
Are there any plans on supporting an ARM Build (Raspberry Pi)?

**Comment by szwacz** [comment]
I can't provide such, because have no device to test it on.
Also do you think about just having release process for ARM, or actually developing on ARM?

**Comment by pkunze** [comment]
Well, a release would be sufficient, will say: AWESOME. I will receive a PI in a few days and i'll give it a try to see if it already works. According to https://github.com/atom/electron/pull/2094 it could already be possible...

**Comment by pkunze** [comment]
So.. installing and starting on a pi was no problem, but creating a release builds an amd64 architecture .deb-file which is not accepted when trying to `dpkg -i`.

**Comment by pkunze** [comment]
I'd like to add that one can install it on a RPi 2 if you add amd64 to allowed architectures first, which is pretty dangerous one could say:

```bash
$ sudo dpkg --add-architecture amd64
$ sudo dpkg -i releases/electron-boilerplate_#.#.#_amd64.deb
```
Then i was able to start it via menu-item normally:

![bildschirmfoto 2016-03-10 um 10 56 12](https://cloud.githubusercontent.com/assets/1416798/13665872/cb9e49f2-e6ae-11e5-997f-fb078a763b3a.png)

Look at this beauty:

![bildschirmfoto 2016-03-10 um 10 57 35](https://cloud.githubusercontent.com/assets/1416798/13665889/ea0a8590-e6ae-11e5-889b-b135649a454e.png)

You cannot remove `amd64` afterwards, as deb somehow keeps track of used architectures.
The electron build however is made for arm since release ran on the PI, so i guess its just a problem with the Packages Meta info, but i wasn't able to define armhf as the use architecture using dpkg....

As for the Raspberry, this problem will kinda solve its self, as the RPi 3 now natively supports 64 bit I guess. Once I get one into my fingers, I will try this out.

**Comment by carlosperate** [comment]
> now natively supports 64 bit I guess

They are still evaluating if moving the OS to 64 bits is worth the effort. From my point of view it isn't (maintaining 2 operating systems and recompiling all packages), so I'd be surprised if they do the move any time soon.

**Comment by carlosperate** [comment]
Since this is using the prebuild version of electron, which is build for a generic ARMv7 architecture, it should be fine for the majority of single-board computers, as long as there is no real code compilation happening during the packaging I think we are pretty safe.

**Comment by pkunze** [comment]
Yeah, bist as i said, in Order to install i had to add amd64 to Supportes archs which isn't ideal IMO.

**Comment by szwacz** [comment]
I'm totally not familiar with Rasberry world. 
- So this is ordinary debian linux disctribution?
- I see on screenshots you use some kind of VM. I have no idea how CPU virtualization works underneath, but is it physically possible to virtualize ARM on intel processor?

**Comment by szwacz** [comment]
Ok, lame me. VNC Viewer is like "remote control". Right?

**Comment by pkunze** [comment]
Yep. Haven't heard of any way to virtualize this on Intel though.

**Comment by carlosperate** [comment]
You can virtualise it using something like QEMU, but it would definitely require modifications to the linux kernel, even if you use the one provided by Raspberry Pi, although I'd be surprised if somebody hasn't done that already and published it.

Raspbian is in essence a customised version of Debian for ARM, with performance updates and a bunch useful packages for the Pi (I hope it doesn't sound like I'm belittling the effort put into the OS though, I'm sure a lot of people have work quite hard to get it run as best as possible). I believe it is still compiled for ARMv6, which is somewhat old version of the architecture, so that the same image can be used on the old Rasberry Pi 1s and the new Zero, while the Electron ARM is only available for ARMv7 (so the Pi 2 and 3).

I think we need to find a cleaner way to create the boilerplate packages without adding the amd64 architecture flag, at that point I'm sure we can get a few people to test it to make sure it works. I'll be happy to test a working solution on different platforms, but unfortunately I don't really have much time in the very near future to help with the solution itself.

**Comment by TomAshley303** [comment]
My Pi 3 model B is on it's way. I'd like to help test in any way possible.

**Comment by szwacz** [comment]
Now this project uses [electron-builder](https://github.com/electron-userland/electron-builder), so if you still want to have ARM build you might want to check capabilities of that tool (or file a feature request).

**Comment by Booligoosh** [comment]
I'm on a Raspberry Pi 3.
However, when I run
`$ sudo dpkg --add-architecture amd64`
it has an error downloading and says some files were not found. Any advice?

**Comment by black-snow** [comment]
@Booligoosh I fear this has nothing to do with this boilerplate. Grab the error message and throw it into your favorite search engine or pay a visit to stackoverflow ;)

**Comment by Booligoosh** [comment]
@black-snow According to [this answer](http://stackoverflow.com/a/27268043) it seems like won't be able to use the command on a raspberry pi
