### ISSUE TITLE
Airbnb JavaScript Style Guide?

### ISSUE THREAD

**Issue by szwacz** [szwacz/electron-boilerplate#125]
Hello everyone interested!

I'm thinking about making this project obey [airbnb-styleguide](https://github.com/airbnb/javascript) and integrate [eslint](http://eslint.org/).

But I have general problem with introducing more tools here just not to overwhelm newcomers.

Any thoughts?

**Comment by black-snow** [comment]
My two cents:

I use the boilerplate to kickstart my apps. Often there's not much code involved so that I don't feel the need to write clean code at all. If an app gets bigger my own code rules / my company's rules apply. The stuff that the boilerplate does is good to grasp and hacking the boilerplate has not yet been an issue.

I probably just wouldn't use it. I plug my own things in just where and when I need them. 
But as long as it's **fully optional** I also wouldn't mind. *Imho* this okay as longs as I don't need to touch any of my existing or future code if I *don't* wanna use this.

*Apart from all this, thank you very much for keeping this alive and pushing it forward.*

**Comment by szwacz** [comment]
Thanks @black-snow this is exactly the kind of feedback I wanted. If I introduce eslint here for sure using it will be fully optional.

**Comment by carlosperate** [comment]
To be honest, from my point of view, suggesting a code style and integrating a tool would be kind of like suggesting an IDE, preferences are mostly based on personal opinion and do not add real value to the software itself.

Something like that would be useful to unify the development environment, which makes sense when expecting several developers to constantly collaborate on the project. However, this type of project is likely to be used by a wide range of developers that will never contribute back with the boilerplate and some that might have to adhere to their own code styles and set of tools.

Btw, how would this type optional implementation work?

**Comment by szwacz** [comment]
You convinced me. No styleguide in this project for now.
