### ISSUE TITLE
How can it be debugged in webstorm?

### ISSUE THREAD

**Issue by visualaram** [szwacz/electron-boilerplate#176]
I'm trying to run it with electron-prebuilt on webstorm on a mac but it doesnt work. Any ideas?

**Comment by black-snow** [comment]
It ain't matter which IDE or editor you use. So no, no ideas.
*"It doesn't work"* isn't that helpful. Please be specific. Tell us exactely what you did and what's the outcome.

**Comment by develar** [comment]
You can debug it in IntelliJ Platform IDEs 2016.2+ ASAR packaging supported. But some fixes is not yet available in the released versions (if you use unpacked asar files).  Currently, electron 1.3.1+ Electron debugging is broken — https://github.com/electron/electron/issues/6608 Feel free to ping me — I developer of JetBrains JS debuggers. So, you can expect excellent support (because electron-boilerplate uses electron-builder under the hood).

**Comment by develar** [comment]
Consider to close as `question`.
