### ISSUE TITLE
npm run release error

### ISSUE THREAD

**Issue by azl397985856** [szwacz/electron-boilerplate#181]
npm run release to generate installation package, it works, but fails because 'can't find module react'. then I check the  bundle fule, just find the bundle file only  have the business code, third party code like react was not bundled correctly

note that I modified the task/bundle.js
rollup.rollup({
        entry: src,
     +   plugins: [
     +     babel()
     + ],

**Comment by azl397985856** [comment]
Object.keys(appManifest.dependencies)
returned  [ 'fs-jetpack', 'react', 'react-dom', 'antd' ]

**Comment by black-snow** [comment]
What's missing exactely? If you want to have additional js files merged or copied you may have to add some more lines to the build task (line 50+).

**Comment by azl397985856** [comment]
![image](https://cloud.githubusercontent.com/assets/12479470/16675226/b80ea548-44f1-11e6-838b-aa13e675f4ee.png)
this is my build folder.  the node_modules here, why not bundled into app.js? Im getting puzzled

**Comment by black-snow** [comment]
Take a look at [tasks/build.js](https://github.com/szwacz/electron-boilerplate/blob/master/tasks/build/build.js).

```javascript
var bundleApplication = function () {
    return Q.all([
            bundle(srcDir.path('background.js'), destDir.path('background.js')),
            bundle(srcDir.path('app.js'), destDir.path('app.js')),
        ]);
};
```
Seems like it won't bundle stuff from `node_modules` by default. You should be fine to just `require()` your components the normal way. If you really need to have stuff from `nodue_modules` bundled into another file then you'll have to edit `tasks/build.js`.

E. g.:

```javascript
var bundleApplication = function () {
    return Q.all([
            bundle(srcDir.path('background.js'), destDir.path('background.js')),
            bundle(srcDir.path('app.js'), destDir.path('app.js')),
            bundle(srcDir.path('node_modules/react/some_script.js'), destDir.path('app.js')), // bundled into app.js
            bundle(srcDir.path('node_modules/some_other_module/index.js'), destDir.path('some_other.js')), // bundled into some_other.js
        ]);
};
```

**Comment by azl397985856** [comment]
that's to say, if src//app.js import react as dependence,react wont'b be bundled into the build//app.js
So I have to change the build task manually when import other pakages

**Comment by szwacz** [comment]
Rollup has configuration option called `external`: https://github.com/szwacz/electron-boilerplate/blob/master/tasks/build/bundle.js#L30
All modules listed there will not be bundled. In electron there is no need to bundle everything together because the files won't be transferred via network (also bundling is not an option for native modules). So this boilerplate is by default configured to leave everything in `node_modules` as it is (not bundling).

Rollup will change all imports to proper require statements, so everything should work fine (maybe babel is messing something up here). That being said you can bundle all stuff from node_modules, but I believe you need one extra rollup plugin for that: https://github.com/rollup/rollup-plugin-node-resolve
