### ISSUE TITLE
How do I use spectron with the build/test process?

### ISSUE THREAD

**Issue by brandoncc** [szwacz/electron-boilerplate#195]
I have been trying to figure out how to use `npm test` with spectron. I have a file at "tests/features/index.spec.js" with the following contents:

```js
var Application = require('spectron').Application;
var electron = require('electron-prebuilt');
var assert = require('assert');

describe('application launch', function () {
  this.timeout(10000);

  beforeEach(function () {
    this.app = new Application({
      path: '/Users/brandoncc/dev/myapp/dist/mac/MyApp.app/Contents/MacOS/MyApp'
    });
    return this.app.start();
  });

  afterEach(function () {
    if (this.app && this.app.isRunning()) {
      return this.app.stop();
    }
  });

  it('shows an initial window', function () {
    return this.app.client.getWindowCount().then(function (count) {
      assert.equal(count, 1)
    });
  });
});
```

all I get is that the chrome driver didn't start within 500ms. Please help. I also tried starting it using the main script and the `Electron` executable, but I get es6 syntax related errors. I tried finding where background.js is compiled to, but I haven't been successful yet.

**Comment by szwacz** [comment]
Actually I have Spectron integration in my todos for next week :)

I've started tinkering with it some time ago on separate branch: https://github.com/szwacz/electron-boilerplate/tree/e2e/e2e But this code is obsolete, since we use `electron-builder` now.

You need completely separate "way" for this than already implemented `npm test`.
First of all, you need to build the final app package (Spectron is testing the whole app, not just files), there is handy option for than in `electron-builder` (`--dir` flag).

So I imagine it something like this...
1. define pree2e script which builds the app with `--dir` flag
2. define e2e script which launches mocha with your test files. And you want to add `mocha` as dependency along `electron-mocha` to your project. Running Spectron tests in `electron-mocha` will give you inception like feeling I believe.

As I said I'm about to integrate it here. But if you'll have something faster than me don't hesitate to submit a PR :)

**Comment by brandoncc** [comment]
I actually got further, by changing `buildTask` in the build task for gulp:

```js
var bundleTask = function () {
  if (utils.getEnvName() === 'test') {
    return Q.all([
      bundleApplication(),
      bundleSpecs()
    ]);
  }
  return bundleApplication();
};
```

Now I get an error saying that `on` is undefined because `require('electron')` isn't pulling in electron. I haven't figured out why or how to fix that though. I guess I'll be waiting for your update. Thanks for an awesome product which really helped me a lot!

**Comment by brandoncc** [comment]
By the way, I think you can run the specs against the built files like this:

```js
this.app = new Application({
  path: '/Users/brandoncc/dev/myapp/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron',
  args: ['/Users/brandoncc/dev/myapp/build/background.js']
});
return this.app.start();
```

This is from the spectron docs:


* `path` -  **Required.** String path to the Electron application executable to
  launch.
  **Note:** If you want to invoke `electron` directly with your app's main
  script then you should specify `path` as  `electron` via `electron-prebuilt`
  and specify your app's main script path as the first argument in the `args`
  array.

I also tried this:

```js
var Application = require('spectron').Application;
var electron = require('electron-prebuilt');
var assert = require('assert');

describe('application launch', function () {
  this.timeout(10000);

  beforeEach(function () {
    this.app = new Application({
      path: electron,
      args: ['/Users/brandoncc/dev/myapp/build/background.js']
    });
    return this.app.start();
  });
```

and got the same error. Maybe that helps you in some way?

**Comment by szwacz** [comment]
Spectron integration is live!

**Comment by brandoncc** [comment]
Awesome, I'll rebase and give it a go. Thank you @szwacz!

**Comment by szwacz** [comment]
There are lots of changes in v4.0 of this boilerplate so be careful with rebasing :)

**Comment by brandoncc** [comment]
Okay. I added support for haml, coffeescript, and sass before so I was going to rebase...maybe I will just bring in my project files and do the same again. Thanks again :-)
