### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by blainesch** [szwacz/electron-boilerplate#199]
Your project doesn't have a license file, nor your root package.json file.

There is an MIT license in the [app/package.json](https://github.com/szwacz/electron-boilerplate/blob/master/app/package.json#L9) but I'm unsure if this represents the whole project or not.

Personally, I'd like to see this [unlicense](http://choosealicense.com/licenses/unlicense/) that a few boilerplate have adopted. What do you think?

**Comment by blainesch** [comment]
ah, it's in the readme.

**Comment by szwacz** [comment]
Do you have some lawyer to ask what actually is the difference between MIT and unlicense? For me those are kind of the same sounding.

**Comment by blainesch** [comment]
No, judging just off of the [choose a license](http://choosealicense.com/licenses/) site, MIT says it requires you to "include a copy of the license and copyright notice with the code" where UNLICENSE does not. Most of my code is MIT, but I've been curious about this license for a while.

**Comment by black-snow** [comment]
Afaik there's a huge difference between unlicensed code and MIT licensed code.
For unlicensed stuff you can, at any point in the future, choose to throw any license at it. That's why you shouldn't use any unlicensed code - it can suddenly get licensed and break your neck.

*unlicense* seems to have some issues, please throw your favourite search engine at it.

As you said it's in the readme and already licensed under the MIT license.

**Comment by blainesch** [comment]
The [unlicense](http://unlicense.org/) is a license, but you are right that the project is MIT already. Changing that would require permission from every contributor. That also wasn't my intent, my intent was to find the license since the project repo didn't contain a `LICENSE` file, I missed it.

**Comment by black-snow** [comment]
https://github.com/szwacz/electron-boilerplate/pull/200
