### ISSUE TITLE
plans of having a livereload feature?

### ISSUE THREAD

**Issue by val-samonte** [szwacz/electron-boilerplate#21]
first off, thank you for making this amazing boilerplate! really big help for starters like me on electron. 
anyway, my question is, do you have plans on putting livereload feature in this boilerplate? 

I was trying to integrate electron-connect (https://github.com/Quramy/electron-connect), but as a newbie, i am having a hard time putting it all together.

Thanks!

**Comment by szwacz** [comment]
Thanks @val-samonte.
This electron-connect thing looks promising. I'll give it a shot.

**Comment by szwacz** [comment]
electron-connect is not a good fit for this project, too many other nice things have to be sacrificed in exchange.

I have an idea how to do live reload without it, but would like to see Gulp v4 (what probably won't happen soon) for that to work. Need to think more about it...

In the meantime PRs are welcome!

**Comment by jsumners** [comment]
Looks like gulp 4 could be released soon -- https://github.com/gulpjs/gulp/issues/1302

**Comment by tkdave** [comment]
I just added PR #147 for BrowserSync support.

**Comment by szwacz** [comment]
Oh! I was telling here few months ago that https://github.com/Quramy/electron-connect isn't good solution (forgot about this). Apparently they did serious rewrite since then, because now electron-connect looks quite promising.

Rest of the story is here: https://github.com/szwacz/electron-boilerplate/pull/147#issuecomment-210664041
