### ISSUE TITLE
Whats the best way to add Bower?

### ISSUE THREAD

**Issue by apintocr** [szwacz/electron-boilerplate#220]
Hello,
I'm used to use bower to manage front.ed dependencies (coming from webdev background).

What is the best way to add bower to this boilerplate? inside the app folder or isinde the src folder (since it will get compiled).

I read in a previous closed issue that you are not quite happy with bower, I get it...
Any suggestions as a alternative?

Thank you!

**Comment by black-snow** [comment]
I'm not sure I understand your question. `npm i bower` installs bower.
Do you mean the packages you fetch via bower? If they use *import* statements or other stuff that's not yet there natively they must go in *src* or you'll have to edit the build process.

**Comment by szwacz** [comment]
I'm not unhappy with bower, I just think its time has passed ;) Right now all packages I need are in npm, so there is no need to add extra level of complexity by introducing yet another package manager.

That being said if you want to integrate bower I would do this so that `bower_components` folder is in `app` folder. This way you don't need to make any modificatins to build process, it will just work. You can require the scripts by `<script>` tag or by `require()` if the module supports commonJS.
