### ISSUE TITLE
"import bootstrap";

### ISSUE THREAD

**Issue by distributev** [szwacz/electron-boilerplate#259]
Did anybody manage to properly 

```import 'bootstrap';```

?

I keep get **_Uncaught ReferenceError: jQuery is not defined_**

Here is what I tried.

https://github.com/rollup/rollup/issues/1328

I know that I can hard-code jquery.js and boostrap.js inside  <script> tags in app.html but I would prefer to properly ```import 'bootstrap';```

How this can be done?

**Comment by black-snow** [comment]
Not quite an answer to your question but why don't you just add a `<script>` tag? You need to pull in the CSS anyway, right? I like to keep things together so in my apps it's always like:

```html
<link rel="stylesheet" href="/path/to/bootstrap.min.css" />
<script src="/path/to/bootstrap.min.js" />
```

**Comment by distributev** [comment]
rollup.js is part of this electron boiler plate and supports ES6 modules. I can import all other libraries using ES6 syntax (angular, admin lte) I get issues only with import 'bootstrap';

And actually import 'bootstrap'; technically works too - it's jQuery which is a dependency for bootstrap and which I cannot get it correctly processed to expose the global jQuery (required by bootstrap).

**Comment by szwacz** [comment]
Indeed it looks like jquery doesn't like electron, and bootstrap expects jquery to be globally accessible. So theoretically this should work:
```js
import $ from 'jquery';
window.jQuery = $;
import 'bootstrap';
```
But rollup hoists all imports to the top (what most probably is required by ES6 modules spec), so the code after transpilation looks as follows:
```js
var $ = require('jquery');
require('bootstrap');
window.jQuery = $;
```
And won't work :)

So, actually there is no way to do it without a hack. And the hack is to use `require` instead of `import` for those two lines as an exception case:
```js
window.jQuery = require('jquery');
require('bootstrap');
```
