### ISSUE TITLE
Use of requirejs() vs <script> tags

### ISSUE THREAD

**Issue by quadrophobiac** [szwacz/electron-boilerplate#27]
I've been trying to build on your repo to develop my own understanding of TDD when making an Electron App (your repo is the best integrated solution I've found)

I'm wondering if you could explain how you picture the `requirejs()` function working in the `index.html`. I was under the impression that requirejs helped managed loading all javascripts, however `app.html` still includes `<script src= ...>` tags. Also app.js (which is loaded by require) also includes module loading therein.

Is the intention for app.js to act as a central javascript file where all modules (either ES6 module pattern or commonJS pattern) are loaded that will be used by the webpage. It would be helpful to understand the javascript module loading pattern intended

**Comment by szwacz** [comment]
Ok, this is a little complicated, so I hope I'll be able to deliver it clearly :)

Electron is acutally Node.js (ok, io.js) + Browser (Chromium) tied together. On the node.js side you have npm which uses commonJs modules through `require()`. That's why I didn't use browserify here - because then you wouldn't be able to use native modules from npm (native are those compiled from C++ like SQLite, scrypt, levelDB and so on). So that's why Require.js (AMD) is used here (require.js can be used with `requirejs()` keywrd what leaves `require()` intact so it still resolves modules from `node_modules` folder. 

Sidenote: Require.js works by including starting `<script>` in the html, and then the script adds more script tags as next modules are needed. So after all everything ends as just script tag in app.html file.

BUT require.js is only for the main body of code you're writing, nothing prevents you from adding extra `<script>` tags with whatever you like (like jquery, analytics, developer helpers etc.) which you want to be loaded immedately, without all the requirejs hassle. So both require.js and plain `<script>` tags can actually coexist next to each other peacefully and we can take advantage of it.

Does that make sense?

**Comment by quadrophobiac** [comment]
Thank you so much for the quick reply! I tried to reply last night but I was too bleary eyed to formulate the right response.
I think I've understood this correctly: in your code you've used script tags with self-executing anonymous functions - is the reason such functions aren't loaded by requirejs is because there isn't a need to be able to invoke those methods continuously through the lifetime of an app (i.e. that they are `one shot` lines of code)
I have a follow up question:
1. your example `app.js` file demonstrates that both UMD (the files in `hello_world` directory) and node native modules. I followed the exact CommonJS pattern you used to describe the `window_state` module (in `vendor/electron_boilerplate`) to write a module and found that I could also load that within `app.js`. As you did in `window_state.js` I included some electron modules via node `require()` invocation.
Q: My question with respect to the above is whether this sort of nested (or cascading?) module invocation is a good or bad idea? From what I understand of AMD it seems like this pattern of dependency declaration runs counter to the organisational benefits of AMD require 
My second question is much more succinct.

Thanks again in advance!

**Comment by szwacz** [comment]
You just made me realise that javascript modules is a bigger mess than I thought ;)

Actually you asked very good question. Why I added the helper scripts from vendor/electron-boilerplate in self-invoking functions. I did this for few reasons.
1. those scripts will load no matter what will happen to require.js
- for example if I made a syntax error in some application file and require.js will fail to load I still can hit CTRL+R to reload the page, because helper script which does that has been loaded in separate <script>
2. the scripts from vendor/electron-boilerplate are quite special purpose helpers (and always global), so I thought what the hell - why not require them this way.
3. This way file app.js it totally in your control and no my line of code has to stay there ;)

This decission is not something I have very strong reasons behind. You can easily get it to work requireing them as everything else.

**Comment by jonatasfreitasv** [comment]
I fix it in my pull request #33 ;).
