### ISSUE TITLE
Special precautions for Windows

### ISSUE THREAD

**Issue by iiiich** [szwacz/electron-boilerplate#28]
First, thank you for the great boilerplate. It makes it easy to get the right start with electron.

I wonder wich Path I have to set for a Windows Release. I installed NSIS and seted the System Environment like that
```
setx PATH "%PATH%;C:/Program Files (x86)/NSIS"
```
but like that I get the following error:
```console
[13:06:28] Building installer with NSIS...

C:\Users\robert\Desktop\electron-boilerplate\tasks\release_windows.js:101
                + " added to PATH environment variable?";
                ^
Can't find NSIS. Are you sure you've installed it and added to PATH environment
variable?

npm ERR! Windows_NT 6.1.7601
```
Maybe you got a hint how the set the System Environment Variable correctly?

Thank you very much.

**Comment by FlipOneDev** [comment]
@iiiich - Windows uses the backslash "\", not the forward-slash "/". So try to edit the PATH System Environment Variable by manually ADDING "C:\Program Files (x86)\NSIS" (without the quotes) to the end of the PATH environment variable. Then save it.

If you're using a command line instance, close it and then open a new one so that the change you made to your PATH environment variable is used.

**Comment by szwacz** [comment]
I don't know how to do it from command line. Always did that through clicking :)
http://www.computerhope.com/issues/ch000549.htm

**Comment by fabdelgado** [comment]
@iiiich my patch works this way:

%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files (x86)\NSIS;

After config reboot system
