### ISSUE TITLE
Boilerplate total failure 

### ISSUE THREAD

**Issue by zorgrian** [szwacz/electron-boilerplate#322]
##  Fundamental failure

![](https://upload.wikimedia.org/wikipedia/commons/1/19/Train_wreck_at_Montparnasse_1895.jpg)

### Boilerplate code

![](https://upload.wikimedia.org/wikipedia/commons/5/54/Ransomes_Sims_and_Jeferies_Badge_IMG_1836.jpg)

### Consider the boilerplates 

When we consider a boilerplate, we really have to have some faith that it is a [boilerplate](https://en.wikipedia.org/wiki/Boilerplate_code). 

As this boilerplate fails to bring in all dependencies because said dependencies are either deprecated or actually do not work with the JavaScript code of the stewing boilerplate, then it is no longer a boilerplate. 

This is a shame as I wanted to see the boilerplate in action.

**Comment by szwacz** [comment]
I’m not sure this conversation is for real, but I will treat it like that.

This project was started in 2016, is mature for few years already and because of its minimalism needs very little maintenance. I’m terrible sorry but I’m not reviewing it every few weeks to see if there is something to update. There is a button that any user of the boilerplate can click to send an issue if they find something is not right, or even better, they can try to fix it themselves and send a PR. This is how open source software is built after all.

I wasn’t aware I have an unpaid job of making people on the internet happy till the end of my life. This is not something I opted for.

The project is also quite labor-intensive to maintain since needs testing on three different operating systems with each change. Therefore this is a great moment to archive electron-boilerplate.

Huge thank you to all good souls who contributed to this codebase through its' life! :)
Have a great 2023 everybody!
