### ISSUE TITLE
Why Trevis-CI is not installed ?

### ISSUE THREAD

**Issue by jonatasfreitasv** [szwacz/electron-boilerplate#34]
This would rather speed up the contribution to the project.

**Comment by szwacz** [comment]
And how do you imagine TravisCI could work on three different operating systems? :)
Even if this would be possible I still can't think of practical use of CI here. Am I missing something?

**Comment by jonatasfreitasv** [comment]
You can run tests to OSX and Linux, but the unit tests by Jasmine can be processed perfectly regardless of operating system.

I will send a Pull Request with unit testing being done with the Karma + Jasmine + PhantomJS, there we will be able to run the unit test with more detail and with Trevis-CI.

**Comment by szwacz** [comment]
Thank you @jonatasfreitasv but you are not testing what your're supposed to be testing with tools you proposed. Electron is not a browser, and can't be fully mocked by phantom.js. You can test electron code only in electron runtime.

**Comment by jonatasfreitasv** [comment]
Electron run js front-end codes in Chromium, is a browser, for Nodejs back-end codes the tests is browser independent, or am I wrong ?

**Comment by szwacz** [comment]
Nope :) You have access to node context everywhere. Everywhere in your code you can do for example `new Buffer('abc')`. Just try it yourself ;)

I see because of this Electron's division to main and window scripts people start to think in terms of backend <-> frontend. I believe this is not the right mindset. Main script is just a manager for windows you want to open (you can open more than one, then everything changes and you need some communication and probably need some logic in main script). There is nothing you can't do in window context (AFAIK) what you can do in main context. Window context is browser and node.js combined, that's where the power really is.
