### ISSUE TITLE
Used Jasmine version

### ISSUE THREAD

**Issue by jonatasfreitasv** [szwacz/electron-boilerplate#36]
Hi again :).

Could send the link of which has been downloaded the Jasmine version used ?

No version I tested, installed via bower or downloaded from Github worked.

**Comment by szwacz** [comment]
There are zip files to download on https://github.com/jasmine/jasmine/releases
I copy contents of `lib/jasminze-x.x.x` directory to `vendor/jasmine`.

**Comment by JimmyBoh** [comment]
@szwacz Do you copy them exactly, or do you make any modifications? I'd like to try to upgrade to the latest release (and if it works I'll make a PR).

**Comment by JimmyBoh** [comment]
Looks like there is some issue with the first few lines of jasmine.js, it's trying to reference `exports` but it is not available. Any idea why this might be @szwacz? If I force it to think it is in the browser it seems to work fine (although my tests are very simple at the moment).

**Comment by szwacz** [comment]
@JimmyBoh Jasmine framework introduced UMD declaration recently. This declaration is troublesome to Electron runtime because Electron is a browser and node.js merged together. https://github.com/szwacz/electron-boilerplate/blob/master/app/vendor/jasmine/jasmine.js#L26

Had to comment manually part of code to make it work. Now this project uses Jasmine 2.4.1

**Comment by JimmyBoh** [comment]
@szwacz Yep, that's exactly what I tried locally. Seeing as the files are included directly in the boilerplate (not pulled in via `npm`) that makes it much easier to change the source to work correctly.
