### ISSUE TITLE
After adding a couple libraries, gulp is extremely slow

### ISSUE THREAD

**Issue by dublinus** [szwacz/electron-boilerplate#58]
I installed jquery and semantic-ui to my project by adding the following dependencies into app/package.json:

    "jquery": "1.11.3",
    "semantic-ui": "2.1"

When I do `npm start`, I see the following:

    [22:43:53] Using gulpfile ~/Documents/analyzerii/gulpfile.js
    [22:43:54] Starting 'clean'...
    [22:43:54] Finished 'clean' after 4.43 ms
    [22:43:54] Starting 'bundle'...
    [22:43:54] Starting 'less'...
    [22:43:54] Starting 'copy'...
    [22:43:54] Starting 'finalize'...
    [22:43:54] Finished 'finalize' after 11 ms
    [22:43:54] Finished 'bundle' after 105 ms
    [22:43:54] Finished 'less' after 136 ms
    [22:44:39] Finished 'copy' after 45 s
    [22:44:39] Starting 'build'...
    [22:44:39] Finished 'build' after 14 μs

Why is "copy" taking 45s? Also, assuming this is just copying some files, why does it take so much of my cpu time and spin up my fans?

**Comment by szwacz** [comment]
Hmm, interesting. Could you tell me the total number of files and directories with subfolders in the directory you want to copy? Is this some staggering number?

**Comment by dublinus** [comment]
24606 files. Yes, I think I may have found the problem.

**Comment by dublinus** [comment]
Most of the files seem to be in node_modules. Is this an abnormal number of files? It seems like it, but I'm new to node.

**Comment by szwacz** [comment]
Yes, node_modules easily can get to thousands of files, because modules install sub-modules they depend on and the nesting of modules can get nasty pretty quiclky.

But you for sure spotted problem here, can you share your package.json file so I can install those dependencies and tinker with the problem?

**Comment by dublinus** [comment]
Of course:

    {
      "name": "Analyzer",
      "productName": "Analyzer",
      "identifier": "",
      "description": "",
      "version": "0.1.0",
      "author": "Hassan",
      "main": "background.js",
      "config": {
        "target": "development"
      },
      "dependencies": {
        "fs-jetpack": "^0.7.0",
    	"jquery": "1.11.3",
    	"semantic-ui": "2.1"
      }
    }

Basically, it's just the jetpack dependency plus the two new ones I added. Thanks for your help.

**Comment by szwacz** [comment]
Holy crap! So `semantic-ui` it the clear culprit here, and boy it installs ton of stuff (120MB uncompressed). I don't know this library so can't tell how to use it more efficiently, but in this state this is not best fit for desktop application which you need to package and ship to the users via installer.
Maybe (just maybe, I might be talking nonsense here because I don't know how the library works) you can install it to development `package.json` (in root folder, not in app folder) and just configure semantic to add the `semantic` directory to `app` directory.

**Comment by dublinus** [comment]
Yes I think that might work. Also, I can download smaller parts of it separately, they have that option, and now I know why. I didn't realize it was that bad.

I will definitely try to install it to development only, thank you for your help!

**Comment by dublinus** [comment]
Okay, what I did was edited tasks/build.js to move the folder called "semantic" (which has the installed semantic files in it):

    var paths = {
        copyFromAppDir: [
            './node_modules/**',
            './vendor/**',
            './**/*.html',
    		'./semantic/**'
        ],
    }

This allowed me to be able to remove semantic as a dependency in my app/package.json file, making the gulp build process much quicker, because it didn't have to move over semantic's dependencies, which seem to only be necessary to build semantic, not actually use it. Thanks again for you help!
