### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by sergiuwd** [szwacz/electron-boilerplate#63]
I have this <i>config.js</i> file:
<pre>
var config = {};

config.twitter = {};
config.redis = {};
config.web = {};

config.default_stuff =  ['red','green','blue','apple','yellow','orange','politics'];
config.twitter.user_name = process.env.TWITTER_USER || 'username';
config.twitter.password=  process.env.TWITTER_PASSWORD || 'password';
config.redis.uri = process.env.DUOSTACK_DB_REDIS;
config.redis.host = 'hostname';
config.redis.port = 6379;
config.web.port = process.env.WEB_PORT || 9980;

module.exports = config;
</pre>

The file is located inside the <i>app</i> folder. I am trying to include it like this inside my <i>app.js</i> file:
<pre>var config = require('./config');</pre>
But I keep getting this error:
<b>Uncaught Error: Cannot find module './config'</b>

What am I doing wrong?

**Comment by szwacz** [comment]
It's because build process didn't copy this file during build, so the real working application doesn't have it in the right place. You can just convert this to ES6 module and it will start working. If it has to be CommonJS module then you have to explicityly add its path to copy in build task (not recommended :), this project is configured to be used with ES6 syntax).
