### ISSUE TITLE
Babel Support

### ISSUE THREAD

**Issue by Oyed** [szwacz/electron-boilerplate#74]
Any chance you could add Babel support for those of us who want to use ES6 within the Application?

**Comment by szwacz** [comment]
1. Remember that this boilerplate is a starting point, copy of which you can extend and change in any direction you want. You can easily integrate Babel for yourself.

2. This project already used Babel in the past, but I switched to rollup because it gives bundling, which I value more than ES6 features.

3. Keep in mind that Electron runs only the latest chromium engine, so a lot of ES6 features are in place natively without Babel.

**Comment by szwacz** [comment]
O! There is rollup plugin for babel: https://github.com/rollup/rollup-plugin-babel
So probably you can have full babel really easily here :)
